In [9]:
import pandas as pd
import numpy as np

df = pd.read_csv('2016 School Explorer.csv')
df

,Adjusted Grade,New?,Other Location Code in LCGMS,School Name,SED Code,Location Code,District,Latitude,Longitude,Address (Full),...,Grade 8 Math - All Students Tested,Grade 8 Math 4s - All Students,Grade 8 Math 4s - American Indian or Alaska Native,Grade 8 Math 4s - Black or African American,Grade 8 Math 4s - Hispanic or Latino,Grade 8 Math 4s - Asian or Pacific Islander,Grade 8 Math 4s - White,Grade 8 Math 4s - Multiracial,Grade 8 Math 4s - Limited English Proficient,Grade 8 Math 4s - Economically Disadvantaged
0,NaN,NaN,NaN,P.S. 015 ROBERTO CLEMENTE,310100010015,01M015,1,40.721834,-73.978766,"333 E 4TH ST NEW YORK, NY 10009",...,0,0,0,0,0,0,0,0,0,0
1,NaN,NaN,NaN,P.S. 019 ASHER LEVY,310100010019,01M019,1,40.729892,-73.984231,"185 1ST AVE NEW YORK, NY 10003",...,0,0,0,0,0,0,0,0,0,0
2,NaN,NaN,NaN,P.S. 020 ANNA SILVER,310100010020,01M020,1,40.721274,-73.986315,"166 ESSEX ST NEW YORK, NY 10002",...,0,0,0,0,0,0,0,0,0,0
3,NaN,NaN,NaN,P.S. 034 FRANKLIN D. ROOSEVELT,310100010034,01M034,1,40.726147,-73.975043,"730 E 12TH ST NEW YORK, NY 10009",...,48,1,0,0,0,0,0,0,0,0
4,NaN,NaN,NaN,THE STAR ACADEMY - P.S.63,310100010063,01M063,1,40.724404,-73.986360,"121 E 3RD ST NEW YORK, NY 10009",...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1267,NaN,NaN,NaN,FAMILY LIFE ACADEMY CHARTER SCHOOL,320900860839,84X705,9,40.840277,-73.918654,"14 W 170TH ST BRONX, NY 10452",...,47,1,0,1,0,0,0,0,0,1
1268,NaN,NaN,NaN,HARRIET TUBMAN CHARTER SCHOOL,320900860823,84X706,9,40.832272,-73.905817,"3565 3RD AVE BRONX, NY 10456",...,58,9,0,8,1,0,0,0,0,5
1269,NaN,NaN,NaN,ICAHN CHARTER SCHOOL,320900860835,84X717,9,40.839176,-73.904982,"1525 BROOK AVE BRONX, NY 10457",...,31,7,0,3,4,0,0,0,0,5
1270,NaN,NaN,NaN,BRONX CHARTER SCHOOL FOR BETTER LEARNING,321100860855,84X718,11,40.888739,-73.847787,"3740 BAYCHESTER AVE ANNEX BRONX, NY 10466",...,0,0,0,0,0,0,0,0,0,0
1271,NaN,NaN,NaN,BRONX CHARTER SCHOOL FOR THE ARTS,320800860846,84X730,8,40.821798,-73.886463,"950 LONGFELLOW AVE BRONX, NY 10474",...,0,0,0,0,0,0,0,0,0,0

In [18]:
df.iloc[:, 15:]

,Community School?,Economic Need Index,School Income Estimate,Percent ELL,Percent Asian,Percent Black,Percent Hispanic,Percent Black / Hispanic,Percent White,Student Attendance Rate,...,Grade 8 Math - All Students Tested,Grade 8 Math 4s - All Students,Grade 8 Math 4s - American Indian or Alaska Native,Grade 8 Math 4s - Black or African American,Grade 8 Math 4s - Hispanic or Latino,Grade 8 Math 4s - Asian or Pacific Islander,Grade 8 Math 4s - White,Grade 8 Math 4s - Multiracial,Grade 8 Math 4s - Limited English Proficient,Grade 8 Math 4s - Economically Disadvantaged
0,Yes,0.919,"$31,141.72",9%,5%,32%,60%,92%,1%,94%,...,0,0,0,0,0,0,0,0,0,0
1,No,0.641,"$56,462.88",5%,10%,20%,63%,83%,6%,92%,...,0,0,0,0,0,0,0,0,0,0
2,No,0.744,"$44,342.61",15%,35%,8%,49%,57%,4%,94%,...,0,0,0,0,0,0,0,0,0,0
3,No,0.860,"$31,454.00",7%,5%,29%,63%,92%,4%,92%,...,48,1,0,0,0,0,0,0,0,0
4,No,0.730,"$46,435.59",3%,4%,20%,65%,84%,10%,93%,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1267,No,0.832,"$27,243.69",19%,0%,20%,77%,97%,1%,95%,...,47,1,0,1,0,0,0,0,0,1
1268,No,0.825,"$24,172.46",11%,0%,68%,31%,98%,1%,94%,...,58,9,0,8,1,0,0,0,0,5
1269,No,0.724,"$26,422.05",2%,0%,54%,45%,99%,1%,95%,...,31,7,0,3,4,0,0,0,0,5
1270,No,0.544,"$47,192.42",2%,2%,86%,9%,95%,1%,95%,...,0,0,0,0,0,0,0,0,0,0
1271,No,0.840,"$29,096.71",15%,1%,28%,67%,96%,2%,93%,...,0,0,0,0,0,0,0,0,0,0